import { TooltipProvider } from '@/components/ui/tooltip';
import Provider from '@/context/client-provider';
import ReduxProvider from '@/redux/provider';
import { authOptions } from '@/utils/authOptions';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { Inter } from 'next/font/google';
import 'remixicon/fonts/remixicon.css';
import 'tailwindcss/tailwind.css';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Job on board',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.png',
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.variable}>
        <Provider session={session}>
          <TooltipProvider>
            <ReduxProvider>
              <div>{children}</div>
            </ReduxProvider>
          </TooltipProvider>
        </Provider>
      </body>
    </html>
  );
}
